#!/usr/bin/env bash
# A bash script to install nginx server

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' >/var/www/html/index.nginx-debian.html
service nginx start
