#!/usr/bin/env bash
# A bash script to install nginx server

sudo apt-get -y update
sudo apt-get -y install nginx
touch /var/www/html/index.html
echo "Hello World!" >/var/www/html/index.html
printf %s "server {
  listen      80 default_server;
  listen      [::]:80 default_server;

  root        /var/www/html;
  index       index.html index.htm index.nginx-debian.html
}
" >/etc/nginx/sites-available/default

service nginx start
