#!/usr/bin/env bash
# A bash script to install nginx server

sudo su <<EOF
apt-get -y update
apt-get -y install nginx
echo 'Hello World!' >/var/www/html/index.nginx-debian.html
sid -i '/server_name _;/a rewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;' /etc/nginx/sites-available/default
service nginx restart
EOF
