#!/usr/bin/env bash
# A bash script to install nginx server

sudo su <<EOF
apt-get -y update
apt-get -y install nginx
echo 'Hello World!' >/var/www/html/index.nginx-debian.html
sed -i 'listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/ngnix/sites-available/default
service nginx restart
EOF
