#!/usr/bin/env bash
# A bash script to install nginx server

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' >/var/www/html/index.nginx-debian.html
sed -i '24i\    rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/ngnix/sites-available/default
sudo service nginx restart
