#!/usr/bin/env bash
# A bash script to install nginx server

sudo -s <<EOF
apt-get -y update
apt-get -y install nginx
echo 'Hello World!' >/var/www/html/index.nginx-debian.html
chmod 755 /etc/nginx/sites-available/default
sed -i '/server_name _;/a\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/error_404.html
sed -i '/redirect_me/a\terror_page 404 /error_404.html;' /etc/nginx/sites-available/default
service nginx restart
EOF
