#!/usr/bin/env bash
# To configure a new machine running Ubuntu.

sudo apt-get -y update
sudo apt-get -y install nginx

HOST=$(hostname)
HEADER="\\\n\tadd_header X-Served-By $HOST;\n"
WHERE=$(grep "X-Served-By" /etc/nginx/sites-available/default)
if [[ -z $WHERE ]]; then
	sed -i "23i $HEADER" /etc/nginx/sites-available/default
fi

echo "Hello World!" >/var/www/html/index.html

WHERE=$(grep "redirect_me" /etc/nginx/sites-available/default)
STR="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
if [[ -z $WHERE ]]; then
	sed -i "42i $STR" /etc/nginx/sites-available/default
fi

WHERE=$(grep "error_page 404" /etc/nginx/sites-available/default)
ERR="\\\n\terror_page 404 /error_404.html;\n"
if [[ -z $WHERE ]]; then
	echo "Ceci n'est pas une page" >/var/www/html/error_404.html
	sed -i "40i $ERR" /etc/nginx/sites-available/default
fi

service nginx restart
