#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

sudo su <<EOF
apt -y update;
apt -y install nginx
ufw allow 'Nginx HTTP'

if [ -d "/var/www" ]
then
  mkdir -p /var/www
fi

chwon -R "$USER":"$USER" /var/www
chmod -R 777 /var/www

# shellcheck disable=SC2154
for dir in /var/www/{html,error}
do
  if ! [ -d "$dir" ]
  then
    mkdir -p "$dir"
  fi
done

echo "Hello World!" > /var/www/html/index.html
chmod 755 /etc/nginx/sites-available/default
sed -i '/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/index.html
sed -i '/redirect_me/a error_page 404 /error_404.html;' /etc/nginx/sites-available/default

EOF
